[build]
builder = "dockerfile"
dockerfilePath = "packages/twenty-docker/twenty/Dockerfile"

[deploy]
startCommand = "node dist/src/main"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
healthcheckPath = "/healthz"
healthcheckTimeout = 10

[[services]]
name = "twenty-server"
startCommand = "node dist/src/main"

[[services]]
name = "twenty-worker"
startCommand = "node dist/src/queue-worker/queue-worker"